In [1]:
import pandas as pd
import numpy as np

In [11]:
df1 = pd.read_csv(r"C:\Users\bhavi\Desktop\sales-performance-analysis\Details.csv")
df2 = pd.read_csv(r"C:\Users\bhavi\Desktop\sales-performance-analysis\Orders.csv")

In [13]:
df1.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [15]:
df2.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [17]:
df = pd.merge(df1,df2)

In [19]:
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,04-06-2018,Bhawna,Madhya Pradesh,Indore
1,B-26055,5729,64,14,Furniture,Chairs,EMI,10-03-2018,Harivansh,Uttar Pradesh,Mathura
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,16-01-2018,Shiva,Maharashtra,Pune
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,27-03-2018,Sarita,Maharashtra,Pune
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,01-04-2018,Vrinda,Maharashtra,Pune

In [21]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
dtype: int64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
 7   Order Date    1500 non-null   object
 8   CustomerName  1500 non-null   object
 9   State         1500 non-null   object
 10  City          1500 non-null   object
dtypes: int64(3), object(8)
memory usage: 129.0+ KB

In [51]:
duplicates = df.duplicated().any()
print(duplicates)

False

In [57]:
top_category = df.groupby('Category')['Amount'].sum().sort_values(ascending=False).head(5)
print(top_category)

Category
Electronics    166267
Clothing       144323
Furniture      127181
Name: Amount, dtype: int64

In [65]:
df['Order Date'].head(10)

0    04-06-2018
1    10-03-2018
2    16-01-2018
3    27-03-2018
4    01-04-2018
5    25-11-2018
6    21-06-2018
7    11-06-2018
8    29-04-2018
9    06-11-2018
Name: Order Date, dtype: object

In [79]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Quarter'] = df['Order Date'].dt.to_period('Q')
df['Quarter Num'] = df['Order Date'].dt.quarter
df['Quarter Num'].head(10)

0    2
1    1
2    1
3    1
4    2
5    4
6    2
7    2
8    2
9    4
Name: Quarter Num, dtype: int32

In [103]:
quarterly_performance = df.groupby('Quarter Num')['Amount'].sum().reset_index()

In [105]:
print(quarterly_performance)

   Quarter Num  Amount
0            1  161288
1            2   87081
2            3   71741
3            4  117661

In [109]:
quarterly_performance = quarterly_performance.sort_values(by='Amount',ascending= False)

In [111]:
print(quarterly_performance)

   Quarter Num  Amount
0            1  161288
3            4  117661
1            2   87081
2            3   71741