In [1]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv(r"C:\Users\bhavi\Desktop\sales-performance-analysis\Details.csv")
df2 = pd.read_csv(r"C:\Users\bhavi\Desktop\sales-performance-analysis\Orders.csv")

In [13]:
df1.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [15]:
df2.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [5]:
df = pd.merge(df1,df2)

In [19]:
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,04-06-2018,Bhawna,Madhya Pradesh,Indore
1,B-26055,5729,64,14,Furniture,Chairs,EMI,10-03-2018,Harivansh,Uttar Pradesh,Mathura
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,16-01-2018,Shiva,Maharashtra,Pune
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,27-03-2018,Sarita,Maharashtra,Pune
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,01-04-2018,Vrinda,Maharashtra,Pune

In [21]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
dtype: int64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
 7   Order Date    1500 non-null   object
 8   CustomerName  1500 non-null   object
 9   State         1500 non-null   object
 10  City          1500 non-null   object
dtypes: int64(3), object(8)
memory usage: 129.0+ KB

In [51]:
duplicates = df.duplicated().any()
print(duplicates)

False

In [57]:
top_category = df.groupby('Category')['Amount'].sum().sort_values(ascending=False).head(5)
print(top_category)

Category
Electronics    166267
Clothing       144323
Furniture      127181
Name: Amount, dtype: int64

In [65]:
df['Order Date'].head(10)

0    04-06-2018
1    10-03-2018
2    16-01-2018
3    27-03-2018
4    01-04-2018
5    25-11-2018
6    21-06-2018
7    11-06-2018
8    29-04-2018
9    06-11-2018
Name: Order Date, dtype: object

In [79]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Quarter'] = df['Order Date'].dt.to_period('Q')
df['Quarter Num'] = df['Order Date'].dt.quarter
df['Quarter Num'].head(10)

0    2
1    1
2    1
3    1
4    2
5    4
6    2
7    2
8    2
9    4
Name: Quarter Num, dtype: int32

In [103]:
quarterly_performance = df.groupby('Quarter Num')['Amount'].sum().reset_index()

In [105]:
print(quarterly_performance)

   Quarter Num  Amount
0            1  161288
1            2   87081
2            3   71741
3            4  117661

In [109]:
quarterly_performance = quarterly_performance.sort_values(by='Amount',ascending= False)

In [111]:
print(quarterly_performance)

   Quarter Num  Amount
0            1  161288
3            4  117661
1            2   87081
2            3   71741

In [43]:
state_perf =  df.groupby('State')['Amount'].sum().sort_values(ascending= False).head(5)

In [9]:
print(state_perf)

State
Maharashtra       102498
Madhya Pradesh     87463
Uttar Pradesh      38362
Delhi              22957
Rajasthan          22334
Name: Amount, dtype: int64

In [49]:
city_perf = (
    df.groupby('City')['Amount']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(city_perf)

City
Indore                63680
Mumbai                58886
Pune                  43612
Mathura               28747
Bhopal                23783
Delhi                 22957
Chandigarh            21142
Ahmedabad             14543
Kolkata               14328
Thiruvananthapuram    13871
Name: Amount, dtype: int64

In [65]:
### top_states = state_perf.index
top_state_df = df[df['State'].isin(top_states)]
top3 = (
    top_state_df
    .groupby(['State', 'City'])['Amount']
    .sum()
    .groupby(level=0)
    .nlargest(1)
    .sort_values(ascending=False)
)

print(top3)

State           State           City
Madhya Pradesh  Madhya Pradesh  Indore     63680
Maharashtra     Maharashtra     Mumbai     58886
Uttar Pradesh   Uttar Pradesh   Mathura    28747
Delhi           Delhi           Delhi      22957
Rajasthan       Rajasthan       Jaipur     11261
Name: Amount, dtype: int64

In [ ]:
popular_payment_modes = df.

In [71]:
payment_counts = df['PaymentMode'].value_counts()
print(payment_counts)

PaymentMode
COD            684
UPI            331
Debit Card     202
Credit Card    163
EMI            120
Name: count, dtype: int64

In [75]:
payment_mode_revenues = df.groupby('PaymentMode')['Amount'].sum().reset_index()
print(payment_mode_revenues)

   PaymentMode  Amount
0          COD  155181
1  Credit Card   86932
2   Debit Card   49136
3          EMI   77881
4          UPI   68641

In [79]:
highest_revenue_payment =  payment_mode_revenues.sort_values(by = 'Amount',ascending = False)
print(highest_revenue_payment)

   PaymentMode  Amount
0          COD  155181
1  Credit Card   86932
3          EMI   77881
4          UPI   68641
2   Debit Card   49136

In [85]:
rep_cus = df['CustomerName'].value_counts()
print(rep_cus)

CustomerName
Abhishek     21
Priyanka     21
Shreya       18
Shruti       17
Yogesh       16
             ..
Preksha       1
Rahul         1
Navdeep       1
Snehal        1
Shreyoshe     1
Name: count, Length: 336, dtype: int64